version: "2.2"

services:
    flask:
        build: ./server/flask
        container_name: flask
        restart: always
        environment:
            - APP_NAME=FlaskServer
        expose:
            - 8081
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "5000:5000"